# tasks/setup/debian.yml
---
- name: Set package parameters
  ansible.builtin.set_fact:
    teleport_major_version: "{{ teleport_version.split('.')[0] }}"
    teleport_edition_package: >-
      {% if teleport_edition == 'enterprise' %}teleport-ent{% else %}teleport{% endif %}
  tags: [setup]

- name: Configure APT key
  ansible.builtin.apt_key:
    url: "{{ teleport_gpg_key_url }}"
    state: present
  become: true
  tags: [setup]

- name: Configure repository sources
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/teleport-archive-keyring.gpg]
      {{ teleport_apt_repo_url }}
      {{ teleport_channel }}
    state: present
    update_cache: true
  become: true
  tags: [setup]
