# tasks/setup/redhat.yml
---
- name: Determine repository parameters
  ansible.builtin.set_fact:
    teleport_repo_id: "teleport-{{ teleport_channel | replace('/', '-') }}"
    # teleport_repo_id: "teleport"
    os_major_version: "{{ ansible_distribution_major_version }}"
  tags: [setup]

- name: Add Teleport GPG key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ teleport_gpg_key_url }}"
  become: true
  tags: [setup]

- name: Install repository management utilities
  ansible.builtin.package:
    name: yum-utils
    state: present
  become: true
  tags: [setup]

- name: Configure Teleport repository
  ansible.builtin.yum_repository:
    name: "{{ teleport_repo_id }}"
    description: "Gravitational Teleport {{ teleport_channel }}"
    baseurl: "{{ teleport_yum_baseurl }}/rhel/7/Teleport/$basearch/{{ teleport_channel }}"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ teleport_gpg_key_url }}"
    repo_gpgcheck: true
  become: true
  tags: [setup]
