---
- name: Copy Teleport configuration.
  ansible.builtin.template:
    src: "{{ teleport_config_template }}"
    dest: "{{ teleport_config_path  }}"
    owner: root
    group: root
    mode: 0600
    backup: "{{ teleport_backup_config }}"
  notify: restart teleport
