---
- name: Set fact is_container
  ansible.builtin.set_fact:
    is_container: true
  when: >
    (ansible_virtualization_type is defined and
      (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
    )

- name: "Lookup the cloud server version if none was provided"
  ansible.builtin.include_tasks: detect_cloud_version.yml
  when:
    - teleport_autodetect_version
    - not teleport_version | string

- name: Setup pre-requisites on Redhat Systems
  ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Setup pre-requisites on Debian Systems
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Instalar Teleport via tarball em sistemas não RedHat/Debian
  ansible.builtin.include_tasks: install_via_tar.yml
  when: ansible_os_family not in ['RedHat', 'Debian']

- name: Install Teleport.
  ansible.builtin.package:
    name: "{{ teleport_package }}"
    state: "{{ teleport_package_state }}"
  when: ansible_os_family in ['RedHat', 'Debian']

- name: Create Teleport config
  ansible.builtin.include_tasks: config.yml
  when: teleport_create_config | bool

- name: "Configure systemd service"
  ansible.builtin.include_tasks: "systemd.yml"
  when: teleport_control_systemd

- name: Ensure Teleport is started and enabled at boot.
  ansible.builtin.service:
    name: teleport
    state: started
    enabled: true
