# tasks/main.yml
---

- name: Validations
  tags: [validation]
  block:
    - name: Validate system prerequisites
      ansible.builtin.include_tasks: preflight/check.yml
      tags: [validation, always]
    - name: Detect Teleport version
      ansible.builtin.include_tasks: preflight/version.yml
      tags: [validation, always]

- name: Configure OS environment
  tags: [setup]
  block:
    - name: Install RedHat dependencies
      ansible.builtin.include_tasks: setup/redhat.yml
      when: ansible_os_family == 'RedHat'
    - name: Install Debian dependencies
      ansible.builtin.include_tasks: setup/debian.yml
      when: ansible_os_family == 'Debian'

- name: Install Teleport package
  tags: [install]
  block:
    - name: Install using package manager
      ansible.builtin.include_tasks: install/package.yml
      when: ansible_os_family in ['RedHat', 'Debian']
    - name: Install from tarball
      ansible.builtin.include_tasks: install/tarball.yml
      when: ansible_os_family not in ['RedHat', 'Debian']

- name: Configure cluster authentication
  tags: [security]
  block:
    - name: Retrieve cluster identity
      ansible.builtin.include_tasks: security/ca_pin.yml
    - name: Manage TLS certificates
      ansible.builtin.include_tasks: security/certificate.yml
    - name: Handle authentication config
      ansible.builtin.include_tasks: security/auth.yml

- name: Generate service configuration
  tags: [configuration]
  block:
    - name: Create base configuration
      ansible.builtin.include_tasks: config/main.yml
    - name: Configure proxy settings
      ansible.builtin.include_tasks: config/proxy.yml
      when: teleport_proxy_enabled | bool

- name: Manage Teleport service
  tags: [service]
  block:
    - name: Configure service daemon
      ansible.builtin.include_tasks: service/daemon_management.yml
    - name: Configure systemd integration
      ansible.builtin.include_tasks: service/systemd.yml
      when: teleport_control_systemd | bool
