---
- name: "Set Teleport repository ID based on distribution"
  ansible.builtin.set_fact:
    teleport_repo_id: "{{ teleport_repo_mapping[ansible_distribution] | default(ansible_distribution | lower) }}"
  when: ansible_distribution is defined

- name: "Set OS major version"
  ansible.builtin.set_fact:
    os_major_version: "{{ ansible_distribution_version.split('.')[0] }}"
  when: ansible_distribution_version is defined

- name: "Add Teleport GPG key"
  ansible.builtin.rpm_key:
    key: "{{ teleport_gpg_key_url }}"
    state: present
  become: true
  when: ansible_pkg_mgr in ['yum', 'dnf']

- name: "Install yum-utils package if needed"
  ansible.builtin.package:
    name: yum-utils
    state: present
  become: true
  when: ansible_pkg_mgr in ['yum', 'dnf']

- name: "Add Teleport repository using yum_repository module"
  ansible.builtin.yum_repository:
    name: "teleport"
    description: "Gravitational Teleport packages"
    baseurl: "{{ teleport_yum_baseurl }}/rhel/{{ os_major_version }}/Teleport/{{ ansible_architecture }}/{{ teleport_channel }}"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ teleport_gpg_key_url }}"
  become: true
  when: ansible_pkg_mgr in ['yum', 'dnf']
