---
- name: Configure teleport with systemd
  become: true
  notify: Reload_Teleport
  block:
  - name: Ensure systemd directory exists
    become: true
    ansible.builtin.file:
      dest: "/etc/systemd/system"
      owner: "root"
      group: "root"
      mode: "0755"
      state: directory

  - name: Create teleport service
    become: true
    ansible.builtin.template:
      src: "{{ teleport_service_template }}"
      dest: "/etc/systemd/system/teleport.service"
      owner: "root"
      group: "root"
      mode: "0644"
