# tasks/config/main.yml
---
- name: Manage Teleport configuration lifecycle
  block:
    - name: Backup existing configuration
      ansible.builtin.copy:
        src: "{{ teleport_config_path }}"
        dest: "{{ teleport_config_path }}.bak"
        remote_src: true
        mode: "0600"
      when: teleport_backup_config | bool
      tags: [configuration]

- name: Apply new configuration template
  ansible.builtin.template:
    src: "{{ teleport_config_template }}"  # Normalmente 'templates/default_teleport.yaml.j2'
    dest: "{{ teleport_config_path }}"     # Padrão: '/etc/teleport.yaml'
    owner: "root"
    group: "root"
    mode: "0600"
    validate: "teleport validate --config %s"  # Validação sintática
  notify: Reload Teleport service
  tags: [configuration]

- name: Verify configuration syntax
  ansible.builtin.command:
    cmd: "teleport validate --config {{ teleport_config_path }}"
  changed_when: false
  tags: [configuration, validation]
