---
- name: Ensure configuration directories exist
  tags: [configuration, security]
  block:
    - name: Ensure teleport_config_dir exists
      ansible.builtin.file:
        path: "{{ teleport_config_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0700'
      become: true
      tags: [configuration, security]

    - name: Ensure CA PIN directory exists
      ansible.builtin.file:
        path: "{{ teleport_config_dir }}/security"
        state: directory
        owner: root
        group: root
        mode: '0700'
      tags: [configuration, security]

- name: Enforce CA PIN consistency in configuration
  block:
    - name: Retrieve or update CA PIN from proxy
      ansible.builtin.include_tasks: security/ca_pin.yml
      when: teleport_fetch_ca_pin | bool
      tags: [configuration, security]

    - name: Write CA PIN to configuration file
      ansible.builtin.copy:
        content: "{{ teleport_ca_pin }}"
        dest: "{{ teleport_config_dir }}/security/ca_pin"
        mode: "0600"
        force: false
      tags: [configuration, security]

    - name: Validate final CA PIN format
      ansible.builtin.assert:
        that:
          - (teleport_ca_pin | default('') | regex_search('^sha256:[a-f0-9]{64}$')) is not none
        msg: "Invalid CA PIN format: {{ teleport_ca_pin }}"
      tags: [configuration, security]
