# tasks/config/main.yml
---
- name: Validate and enforce CA PIN security
  block:

    - name: Ensure teleport_config_dir directory exists
      ansible.builtin.file:
        path: "{{ teleport_config_dir }}/security"
        state: directory
        owner: root
        group: root
        mode: '0700'
      become: true
      tags: [configuration, security]

    - name: Ensure CA PIN directory exists
      ansible.builtin.file:
        path: "{{ teleport_config_dir }}/security"
        state: directory
        owner: root
        group: root
        mode: "0700"
      tags: [configuration, security]

    - name: Ensure teleport_proxy_tls_dir directory exists
      ansible.builtin.file:
        path: "{{ teleport_proxy_tls_dir }}/security"
        state: directory
        owner: root
        group: root
        mode: '0700'
      become: true
      tags: [configuration, security]

    - name: Retrieve or validate CA PIN
      ansible.builtin.include_tasks: security/ca_pin.yml
      when: teleport_fetch_ca_pin | bool
      tags: [configuration, security]

    - name: Enforce CA PIN consistency
      ansible.builtin.copy:
        content: "{{ teleport_ca_pin }}"
        dest: "{{ teleport_config_dir }}/security/ca_pin"
        mode: "0600"
        force: false
      tags: [configuration, security]

  always:
    - name: Validate final CA PIN format
      ansible.builtin.assert:
        that: teleport_ca_pin | regex_match('^sha256:[a-f0-9]{64}$')
        msg: "Invalid CA PIN format"
      tags: [configuration, security]

- name: Manage Teleport configuration lifecycle
  block:
    - name: Backup existing configuration
      ansible.builtin.copy:
        src: "{{ teleport_config_path }}"
        dest: "{{ teleport_config_path }}.bak"
        remote_src: true
        mode: "0600"
      when: teleport_backup_config | bool
      tags: [configuration]

    - name: Apply new configuration template
      ansible.builtin.template:
        src: "{{ teleport_config_template }}"
        dest: "{{ teleport_config_path }}"
        owner: "root"
        group: "root"
        mode: "0600"
        validate: "teleport validate --config %s"
      tags: [configuration]

- name: Verify configuration syntax
  ansible.builtin.command:
    cmd: "teleport validate --config {{ teleport_config_path }}"
  changed_when: false
  tags: [configuration, validation]
