---
- name: Reload Teleport service
  ansible.builtin.systemd:
    name: teleport
    state: reloaded
    daemon_reload: yes

- name: Restart Teleport service
  ansible.builtin.service:
    name: teleport
    state: restarted
  when: not is_container | bool

- name: Log configuration change
  ansible.builtin.debug:
    msg: "Teleport configuration was successfully updated"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true
  changed_when: false
