---
- name: Load existing configuration
  ansible.builtin.include_tasks: security/legacy.yml
  when: teleport_config_file.stat.exists

- name: Migrate authentication tokens
  ansible.builtin.set_fact:
    teleport_auth_token: "{{ old_conf.teleport.auth_token }}"
  when:
    - old_conf.teleport.auth_token is defined
    - teleport_auth_token | default('') | length == 0

- name: Handle security changes
  when: security_credentials_changed | bool
  tags: [security]
  block:
    - name: Get current config checksum
      ansible.builtin.stat:
        path: "{{ teleport_config_path }}"
      register: config_check
      changed_when: false
      when: not is_container | bool

    - name: Generate new configuration
      ansible.builtin.command: teleport configure --config={{ teleport_config_path }}
      register: config_generate
      changed_when: config_check.stat.checksum != (teleport_config_path | checksum)
      notify:
        - Restart Teleport service
        - Log configuration change
      when: not is_container | bool

    - name: Flush ephemeral data
      ansible.builtin.file:
        path: "/var/lib/teleport/proc/"
        state: absent
      changed_when: flush_ephemeral_data.files_deleted > 0
      register: flush_ephemeral_data
