---
- name: Retrieve cluster CA PIN from proxy
  ansible.builtin.uri:
    url: "https://{{ teleport_proxy_server }}:443/webapi/auth/export"
    validate_certs: "{{ teleport_validate_certs | default(true) }}"
    return_content: true
    status_code: 200
  register: ca_pin_response
  when:
    - teleport_fetch_ca_pin | bool
    - (teleport_ca_pin | default('')) | length == 0
  tags: [security]

- name: Extract CA PIN from response content
  ansible.builtin.set_fact:
    ca_pin_extracted: "{{ ca_pin_response.get('content', '') | regex_search('(^sha256:[a-f0-9]{64}$)', multiline=True) }}"
  when:
    - teleport_fetch_ca_pin | bool
    - ca_pin_response is defined
  tags: [security]

- name: Set CA PIN fact if extracted value is valid
  ansible.builtin.set_fact:
    teleport_ca_pin: "{{ ca_pin_extracted }}"
  when:
    - teleport_fetch_ca_pin | bool
    - ca_pin_extracted is defined
    - (ca_pin_extracted | length) > 0
  tags: [security]

- name: Assert final CA PIN format
  ansible.builtin.assert:
    that:
      - (teleport_ca_pin | default('') | regex_search('^sha256:[a-f0-9]{64}$')) is not none
    msg: "Invalid CA PIN format: {{ teleport_ca_pin }}"
  tags: [security]
