# tasks/security/certificate_management.yml
---

- name: Ensure teleport_config_dir directory exists
  ansible.builtin.file:
    path: "{{ teleport_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0700'
  become: true
  tags: [configuration, security]

- name: Ensure CA PIN directory exists
  ansible.builtin.file:
    path: "{{ teleport_config_dir }}/security"
    state: directory
    owner: root
    group: root
    mode: "0700"
  tags: [configuration, security]

- name: Ensure teleport_proxy_tls_dir directory exists
  ansible.builtin.file:
    path: "{{ teleport_proxy_tls_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0700'
  become: true
  tags: [configuration, security]

- name: Generate Teleport private key (if not exists)
  community.crypto.openssl_privatekey:
    path: "{{ teleport_proxy_tls_key }}"
    type: RSA
    size: 4096
    mode: '0600'
  become: true
  tags: [security]

- name: Generate a CSR for Teleport
  community.crypto.openssl_csr:
    path: "{{ teleport_csr_path }}"
    privatekey_path: "{{ teleport_proxy_tls_key }}"
    digest: "sha256"
    version: 1
    country_name: "{{ teleport_tls_country | default('BR') }}"
    state_or_province_name: "{{ teleport_tls_state | default('Sao Paulo') }}"
    locality_name: "{{ teleport_tls_locality | default('Sao Paulo') }}"
    organization_name: "{{ teleport_tls_organization | default('Datacosmos') }}"
    common_name: "{{ teleport_proxy_server }}"
    subject_alt_name:
      - "DNS:{{ teleport_proxy_server }}"
  register: teleport_csr
  tags: [security]

- name: Generate self-signed certificate from CSR
  community.crypto.x509_certificate:
    provider: selfsigned
    path: "{{ teleport_proxy_tls_cert }}"
    privatekey_path: "{{ teleport_proxy_tls_key }}"
    csr_path: "{{ teleport_csr_path }}"
    selfsigned_digest: "sha256"
    selfsigned_version: 3
    selfsigned_not_after: "+{{ teleport_tls_valid_days | default(365) }}d"
    selfsigned_create_subject_key_identifier: create_if_not_provided
  tags: [security]
