# tasks/security/certificate_management.yml
---
- name: Generate a CSR for Teleport
  community.crypto.openssl_csr:
    path: "{{ teleport_csr_path }}"
    privatekey_path: "{{ teleport_proxy_tls_key }}"
    subject: >
      /C={{ teleport_tls_country | default('BR') }}
      /ST={{ teleport_tls_state | default('Sao Paulo') }}
      /L={{ teleport_tls_locality | default('Sao Paulo') }}
      /O={{ teleport_tls_organization | default('Datacosmos') }}
      /CN={{ teleport_proxy_server }}
    subject_alt_name: "DNS:{{ teleport_proxy_server }}"
  register: teleport_csr
  tags: [security]


- name: Generate self-signed certificate from CSR
  community.crypto.x509_certificate:
    provider: selfsigned
    path: "{{ teleport_proxy_tls_cert }}"
    privatekey_path: "{{ teleport_proxy_tls_key }}"
    csr_path: "{{ teleport_csr_path }}"
    selfsigned_digest: "sha256"
    selfsigned_version: 3
    selfsigned_not_after: "+{{ teleport_tls_valid_days | default(365) }}d"
    selfsigned_not_before: "now"
    selfsigned_create_subject_key_identifier: create_if_not_provided

  tags: [security]
