# tasks/security/parse_legacy_config.yml
---
- name: Load raw legacy configuration
  ansible.builtin.slurp:
    src: "{{ teleport_config_path }}"
  register: legacy_config_raw
  ignore_errors: true
  tags: [security, migration]

- name: Decode and validate legacy config
  block:
    - name: Parse YAML configuration
      ansible.builtin.set_fact:
        legacy_config: "{{ legacy_config_raw.content | b64decode | from_yaml }}"

    - name: Validate config version
      ansible.builtin.assert:
        that:
          - legacy_config.version == 'v3'
        msg: "Unsupported config version: {{ legacy_config.version }}"

    - name: Extract legacy security parameters
      ansible.builtin.set_fact:
        legacy_auth_token: "{{ legacy_config.teleport.auth_token | default('') }}"
        legacy_ca_pin: "{{ legacy_config.teleport.ca_pin | default('') }}"
      tags: [security, migration]

  rescue:
    - name: Handle legacy config errors
      ansible.builtin.fail:
        msg: "Failed to parse legacy configuration. Manual migration required."
      when: not teleport_force_migration | bool
      tags: [security, migration]
