# tasks/service/systemd.yml
---
- name: Validate systemd availability
  ansible.builtin.command:
    cmd: systemctl --version
  changed_when: false
  register: systemd_check
  ignore_errors: true

- name: Create systemd service unit
  ansible.builtin.template:
    src: "{{ teleport_service_template }}"
    dest: "/etc/systemd/system/teleport.service"
    mode: "0640"
  notify:
    - Reload systemd daemon
    - Restart Teleport service
  when:
    - systemd_check is defined
    - systemd_check.rc == 0
    - not (is_container | bool)
  tags: [service, systemd]

- name: Set service permissions
  ansible.builtin.file:
    path: /etc/systemd/system/teleport.service
    owner: root
    group: root
    mode: "0640"
  tags: [service, systemd]

- name: Ensure service enabled
  ansible.builtin.systemd:
    name: teleport
    enabled: true
    daemon_reload: true
    state: started
  tags: [service, systemd]
