---
name: molecule_tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule: # run weekly, every monday 01:00
    - cron: "0 1 * * 1"

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - molecule_distro: "rockylinux:9"
            experimental: false
          - molecule_distro: "rockylinux:8"
            experimental: false
          - molecule_distro: "ubuntu:22.04"
            experimental: false
          - molecule_distro: "ubuntu:20.04"
            experimental: false
          - molecule_distro: "debian:11"
            experimental: false
    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      MOLECULE_NO_LOG: "false"
      ANSIBLE_ROLE: datacosmos-br.teleport

    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.ANSIBLE_ROLE }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule molecule-plugins docker ansible-lint flake8 testinfra ansible
          # Workaround for https://github.com/docker/docker-py/issues/3113
          pip install "urllib3<2"
      - name: Environment
        run: |
          pwd
          env
          find -ls
      - name: Galaxy dependencies
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
          ansible-galaxy install --timeout 120 --verbose -r molecule/default/requirements.yml --roles-path $HOME/.ansible/roles
        continue-on-error: true
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
          molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
